apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  annotations:
    sealedsecrets.bitnami.com/cluster-wide: "true"
  name: cloudflare-token
  namespace: {{ .Values.namespace }}
  labels:
    app: {{ .Chart.Name }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/name: {{  .Chart.Name }}
    app.kubernetes.io/version: {{ .Chart.AppVersion }}
    helm.sh/chart: {{ .Chart.Name }}-{{ .Chart.Version | replace "+" "_" }}
spec:
  encryptedData:
    token: AgC2D3KU49PPE8VQ7MkXh8LljD2lK+86NwxIQBx0Lyr4q9TbFSlaY+3UcwZey0iQDnsuQfi6NWKIc0XNsYdQtyasY+EpFhaQ+/DFtuMYUFoFqYSF3vlZILDibSgHaQu+TQP57i5217Q3KMrt/K7RZ5FpQ05HveAjZuTFWQeb9gysxb5HqDAKNQTDgLu++IpNmXh+yHd+IAS4btsn5AMpqRh3k4hPLKtBJNXtnStnrFUaZ8QbWEnCh5rEKWr/l3VTm+cJ4KzdYbtnX4fdOsk/Ibpbz5ka2GTos3mJ6Hh1xOfN9HO7ph6Bp9ZighJ4/83E0EJNhrg8po7td689vJ0WIIcaZ+aPK+grF7ivJw1OGq/fCp1Z/JzN7rcH83byEsleLXaBQKUcyRm2LWb5+Ad9BCa3VKiEy90oUmG3oY72PigLvu8PQmrPxEI3VQDPTARejsC6sdSqwpl6HX0xYeSVBqb76ukb6eB3qi1qIPPDY8QNT7966eS4s+QOiSTdU3B3Sqht6fThMD6y5Us05Y+pVG4xLVFJaLCgmEaKVQ1ESnZ5TwhK8HehcMh899k5gHlROe0dpxu16xhEBGec59+jW9kA/4RFCrKab1C1TaZzD5cPa1/IVKK6DfqXNQIamYHszp4xdtfTHGZh7PnWiPoqLDiV0mHhnP0io2Ioo0Ca+a7Lvg8yrb2Ke8FOpiGH3nd5HAtRcVnkppBKlQ+X+yOsMZ1pxO8ddUGGo35g9jjwUVRKNBojgykSmgi2A6/Jm9qhZfFzifuK9qDPiiT5QcEHm2HQdcaKmRNgc5pOJRLIP7mUdO7W1rae9ge9FH8J/Brp/qdlZry+LV9cSv+g9qauXTldYmk4iyCGGQyYD6G6zxzvxRfplPnhCGB0LGUs7qkDYcKXoylwoZWYHjWqOq7iq3KC6ll7Abx8gmj4VntuxCOtFOTxGN+xd/Hw
  template:
    metadata:
      annotations:
        sealedsecrets.bitnami.com/cluster-wide: "true"
      name: cloudflare-token
    type: Opaque
